# API
PHILIPS_HUE_URL = 'http://192.168.1.128/'
USERNAME = 'INSERT_USERNAME'
GROUPS_DIR = 'groups/'
GROUP_ACTION_DIR = 'action/'
LIGHTS_DIR = 'lights/'
LIGHT_STATE_DIR = 'state/'
SCENE_BRIGHT = 'UBc7E1JnIe34g72'
SCENE_DIMMED = 'NUXMowcomM-MWa2'
SCENE_NIGHTLIGHT = 'gFJTd0eLJ7pdzZz'

# control the API
DIM_STEP = 25

# RASPBERRY PI GPIO
GPIO_BUTTON_ON = 4
GPIO_BUTTON_CONNECTION = 25
GPIO_BUTTON_BRIGHTNESS_UP = 23
GPIO_BUTTON_BRIGHTNESS_DOWN = 24
GPIO_BUTTON_PRESET_ONE = 17
GPIO_BUTTON_PRESET_TWO = 27
GPIO_BUTTON_PRESET_THREE = 22
GPIO_BUTTON_NEXT = 16
GPIO_BUTTON_PREVIOUS = 20
GPIO_LED_CONNECT = 14

# I2C
STANDARD_FONT = "/usr/share/fonts/truetype/dejavu/39335_UniversCondensed.ttf"
STANDARD_FONT_SIZE = 34
DISPLAY_WIDTH = 128
DISPLAY_HEIGHT = 32
