# API
PHILIPS_HUE_URL = 'http://192.168.1.128/'
USERNAME = 'INSERT_USERNAME'
GROUPS_DIR = 'groups/'
GROUP_ACTION_DIR = 'action/'
LIGHTS_DIR = 'lights/'

# control the API
DIM_STEP = 25

# RASPBERRY PI GPIO
GPIO_BUTTON_ON = 4
GPIO_BUTTON_CONNECTION = 25
GPIO_BUTTON_BRIGHTNESS_UP = 23
GPIO_BUTTON_BRIGHTNESS_DOWN = 24
